[api]
api_url="https://virtserver.swaggerhub.com/wcd_de_lab/top10/1.0.0/add"

[s3]
bucket='lambda-mini-project-input'
folder='input'

[db]
host='cxiku6uae6ts.us-east-1.rds.amazonaws.com'
port=3306
database='lambda-project'
schema='superstore'

[run]
py_script="run.py"




    

    